package org.mis.profiling.models;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MIGRAIN_ENTRY".
 */
public class MigrainEntry {

    private Long id;
    /** Not-null value. */
    private java.util.Date started;
    /** Not-null value. */
    private java.util.Date ended;
    private double level;
    private String timeofday;
    private String symptoms;
    private String remedy;
    private String medicine;

    public MigrainEntry() {
    }

    public MigrainEntry(Long id) {
        this.id = id;
    }

    public MigrainEntry(Long id, java.util.Date started, java.util.Date ended, double level, String timeofday, String symptoms, String remedy, String medicine) {
        this.id = id;
        this.started = started;
        this.ended = ended;
        this.level = level;
        this.timeofday = timeofday;
        this.symptoms = symptoms;
        this.remedy = remedy;
        this.medicine = medicine;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public java.util.Date getStarted() {
        return started;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStarted(java.util.Date started) {
        this.started = started;
    }

    /** Not-null value. */
    public java.util.Date getEnded() {
        return ended;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEnded(java.util.Date ended) {
        this.ended = ended;
    }

    public double getLevel() {
        return level;
    }

    public void setLevel(double level) {
        this.level = level;
    }

    public String getTimeofday() {
        return timeofday;
    }

    public void setTimeofday(String timeofday) {
        this.timeofday = timeofday;
    }

    public String getSymptoms() {
        return symptoms;
    }

    public void setSymptoms(String symptoms) {
        this.symptoms = symptoms;
    }

    public String getRemedy() {
        return remedy;
    }

    public void setRemedy(String remedy) {
        this.remedy = remedy;
    }

    public String getMedicine() {
        return medicine;
    }

    public void setMedicine(String medicine) {
        this.medicine = medicine;
    }

}
