package org.mis.profiling.models.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import org.mis.profiling.models.User;
import org.mis.profiling.models.MigrainEntry;

import org.mis.profiling.models.dao.UserDao;
import org.mis.profiling.models.dao.MigrainEntryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig migrainEntryDaoConfig;

    private final UserDao userDao;
    private final MigrainEntryDao migrainEntryDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        migrainEntryDaoConfig = daoConfigMap.get(MigrainEntryDao.class).clone();
        migrainEntryDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        migrainEntryDao = new MigrainEntryDao(migrainEntryDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(MigrainEntry.class, migrainEntryDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        migrainEntryDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public MigrainEntryDao getMigrainEntryDao() {
        return migrainEntryDao;
    }

}
